### ISSUE TITLE
Script missing type="module" (or is redundant)

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/web-map-doc#11]
URL: https://maps4html.org/web-map-doc/

Console error: `Uncaught SyntaxError: Cannot use import statement outside a module`.

I'm not certain but I think the source for `<script src="https://maps4html.org/web-map-doc/dist/mapml-viewer.js"></script>` that is loaded (without `type="module"`) is:

https://github.com/Maps4HTML/web-map-doc/blob/b9dc658c403c98b6d799def11f7877f55b967254/docusaurus.config.js#L116-L118

OTOH the embedded map is using its own script with `type="module"`, so perhaps injecting that into head is unnecessary?

**Comment by ahmadayubi** [comment]
Right, that's an artifact from my brief attempt at getting the custom element working on the documentation pages. I think you could probably get rid of either one and still have it work, Keeping the embedded one is definitely going to work as it was originally just that.
