### ISSUE TITLE
Update install instructions and HTML examples for use with CDN

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/web-map-doc#35]
- [ ] Update [install instructions](https://maps4html.org/web-map-doc/docs/installation) per https://github.com/Maps4HTML/Web-Map-Custom-Element/pull/500.
- [ ] Replace relative URLs in HTML examples with absolute URLs (https://unpkg.com/@maps4html/web-map-custom-element@latest/dist/mapml-viewer.js)

**Comment by prushforth** [comment]
Is this still relevant? Should we include it (CDN usage) in web-map-doc?

**Comment by Malvoz** [comment]
Sure.

> Replace relative URLs in HTML examples with absolute URLs (https://unpkg.com/@maps4html/web-map-custom-element@latest/dist/mapml-viewer.js)

We should probably not promote the use of `@latest` though, since it's likely we introduced breaking changes?
