### ISSUE TITLE
Trailing slash bug

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/web-map-doc#41]
1. Go to https://maps4html.org/web-map-doc/docs/
2. Press `<mapml-viewer>` in the nav menu - URL should be https://maps4html.org/web-map-doc/docs/maps/mapml-viewer
3. Paste https://maps4html.org/web-map-doc/docs/maps/mapml-viewer into your browser's adress bar and press enter - URL is now https://maps4html.org/web-map-doc/docs/maps/mapml-viewer/

The issue affects relative links in the documentation.

**Comment by prushforth** [comment]
> The issue affects relative links in the documentation.

What is the impact, exactly? Sorry, I see the effect but not the problem.

**Comment by Malvoz** [comment]
To see the issue:
1. go to https://maps4html.org/web-map-doc/docs/ -> API -> &lt;mapml-viewer&gt; API -> press the "Custom Projection API" link in the table: successfully navigated to https://maps4html.org/web-map-doc/docs/api/custom-projections
2. press this link: https://maps4html.org/web-map-doc/docs/api/mapml-viewer-api (note that a redirect is made to https://maps4html.org/web-map-doc/docs/api/mapml-viewer-api/ (trailing slash) -> press the "Custom Projection API" link in the table: Page not found

**Comment by Malvoz** [comment]
https://docusaurus.io/docs/docusaurus.config.js/#trailing-slash
