### ISSUE TITLE
Add `<featurecaption>` to associated elements of Static Features Layer and in examples

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/web-map-doc#50]
https://maps4html.org/web-map-doc/docs/layers/static-features#associated-elements

**Comment by Malvoz** [comment]
This documentation should highlight the importance of each feature having a unique and descriptive `<featurecaption>`, similar to `alt` for `<img>`.

**Comment by prushforth** [comment]
Page was deleted, but point and issue #104 remains.  Maybe we should make an accessibility tutorial.
