### ISSUE TITLE
Version the documents according to the versioning in Web-Map-Custom-Element

### ISSUE THREAD

**Issue by prushforth** [Maps4HTML/web-map-doc#89]
![image](https://user-images.githubusercontent.com/2437285/204390670-238bcc9f-dd08-463a-b9d5-389a34446afc.png)

**Comment by AliyanH** [comment]
Adding versioning increases complexity and makes it harder to document (as noted by docusaurus [here](https://docusaurus.io/docs/versioning).) We should probably hold off on this for now.
